version: "3.8"

services:
  app:
    image: ace009/user-service-app:latest
    container_name: user_service_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - /var/www/user-service/deployment/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_data:/var/www/html
      - /var/www/user-service/deployment/.env:/var/www/html/.env
      - storage_data:/var/www/html/storage
      - logs_data:/var/www/html/storage/logs
    networks:
      laravel_network:
        aliases:
          - user-service-app
    healthcheck:
      test: ["CMD", "php", "-r", "echo 1;"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: user_service_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/www/user-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_data:/var/www/html
      - storage_data:/var/www/html/storage
      - logs_data:/var/www/html/storage/logs
    depends_on:
      - app
    networks:
      laravel_network:
        aliases:
          - user-service-nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: user_service_mysql
    restart: unless-stopped
    env_file:
      - /var/www/user-service/deployment/.env
    volumes:
      - laravel_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      laravel_network:
        aliases:
          - user-service-mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_mysql_data:
    driver: local
  app_data:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local
  cache_data:
    driver: local
