version: "3.8"

services:
  app:
    image: ace009/user-service-app:latest
    container_name: user_service_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - /var/www/user-service/src/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_data:/var/www/html
      - storage_data:/var/www/html/storage
      - logs_data:/var/www/html/storage/logs
      - /var/www/user-service/src/.env:/var/www/html/.env  # ✅ Fix .env file issue
    expose:
      - "9000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mysql:
    image: mysql:8.2
    container_name: user_service_mysql
    restart: unless-stopped
    env_file:
      - /var/www/user-service/deployment/.env.prod  # ✅ Fix MySQL env file path
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - laravel_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: user_service_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - /var/www/user-service/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  laravel_mysql_data:
    driver: local
  app_data:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local
