version: "3.8"

services:
  app:
    image: ace009/user-service-app:latest
    container_name: user_service_app
    restart: always
    working_dir: /var/www/html
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_data:/var/www/html
    networks:
      laravel_network:
        aliases:
          - user-service-app

  nginx:
    image: nginx:alpine
    container_name: user_service_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_data:/var/www/html
    depends_on:
      - app
    networks:
      laravel_network:
        aliases:
          - user-service-nginx

  mysql:
    image: mysql:8.0
    container_name: user_service_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - laravel_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "&&", "echo", "'MySQL is up'"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      laravel_network:
        aliases:
          - user-service-mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_mysql_data:
    driver: local
  app_data:
    driver: local
