version: "3.8"

services:
  app:
    image: ace009/user-service-app:latest
    container_name: user_service_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_data:/var/www/html
    networks:
      laravel_network:
        aliases:
          - user-service-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: user_service_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_data:/var/www/html
    depends_on:
      - app
    networks:
      laravel_network:
        aliases:
          - user-service-nginx

  mysql:
    image: mysql:8.0
    container_name: user_service_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - laravel_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      laravel_network:
        aliases:
          - user-service-mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_mysql_data:
    driver: local
  app_data:
    driver: local
